modLoader="javafml"
loaderVersion="[38,)"
license="LGPL-3.0"

[[mods]]
modId="beefjerkymod"
version="1.0.2"
logoFile="logo.png"
displayName="Beef Jerky Mod"
description='''
Turns rotten flesh into delicious jerky.
Achieved by slaying zombies and cooking their flesh OR setting them on fire.

Created by LukieDoggo (aka LukieD4 on GitHub).
'''


[[dependencies.beefjerkymod]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.0,)"
    ordering="NONE"
    side="BOTH"
